# Generated by Django 3.2.9 on 2021-11-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='body_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='mod_date',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='pub_date',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='n_pingbacks',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='rating',
        ),
    ]
